version: '3.8'
services:
  backend:
    build: ./backend
    container_name: taskmgr_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/data
    environment:
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
      - DB_PATH=/data/tasks.db
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SECURE=${SMTP_SECURE}
      - EMAIL_FROM=${EMAIL_FROM}
      - REMINDER_EMAIL_TO=${REMINDER_EMAIL_TO}
      - NTFY_BASE=${NTFY_BASE}
      - NTFY_TOPIC=${NTFY_TOPIC}
      - SCHED_INTERVAL_MS=${SCHED_INTERVAL_MS:-60000}
  frontend:
    build: ./frontend
    container_name: taskmgr_frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - backend
